### ISSUE TITLE
Support for astro.js

### ISSUE THREAD

**Issue by sijad** [Applelo/unplugin-inject-preload#8]
I've tried add this vite plugin similar to https://docs.astro.build/en/recipes/add-yaml-support/ but it does not work

related: https://github.com/withastro/astro/issues/7695#issuecomment-1640603818

**Comment by Applelo** [comment]
Hi thanks for the related issue, yes the plugin uses transformIndexHtml hook so if astro doesn't use it, it's not working. I need to make a proper plugin for astro.

**Comment by Applelo** [comment]
After looking for Astro, this needs to be handle to a proper Integration https://docs.astro.build/fr/guides/integrations-guide/. The vite plugin doesn't work with astro because the transformation of _.astro_ file is not handle by transformIndex hook.
So, this plugin will not be compatible for Astro. Maybe if I find time and the need/want to do this, I will rewrite a part of this plugin to provide a helper data to this integration. So I close this issue 😕
